### PR TITLE
Add BASH completion

### LINKED ISSUE #43: Add Bash completions
Create Shell completions

### PR DESCRIPTION
**Pull request by JesterOrNot**
Fixes #43

### CODE REVIEW

**Comment by JesterOrNot** [comment]
@Kreyren what do you think?

**Comment by Kreyren** [comment]
@JesterOrNot eh? you merged a broken commit see review above.

**Comment by JesterOrNot** [comment]
??? It's not broken
image

**Comment by Kreyren** [comment]
@JesterOrNot It's not broken, because you are executing it on bash even with shebang set on /bin/sh because non-POSIX systems does not  do a good job replecating POSIX environment.

Current issues captured by shellcheck:
```
 
Line 3:
    local cur prev opts cmds
    ^-- SC2039: In POSIX sh, 'local' is undefined.
                        ^-- SC2034: cmds appears unused. Verify use (or export if used externally).
 
Line 4:
    COMREPLY=()
    ^-- SC2034: COMREPLY appears unused. Verify use (or export if used externally).
             ^-- SC2039: In POSIX sh, arrays are undefined.
 
Line 5:
    cur="${COMP_WORDS[COMP_CWORD]}"
         ^-- SC2039: In POSIX sh, array references are undefined.
 
Line 6:
    prev="${COMP_WORDS[COMP_CWORD-1]}"
    ^-- SC2034: prev appears unused. Verify use (or export if used externally).
          ^-- SC2039: In POSIX sh, array references are undefined.
 
Line 8:
    if [[ ${cur} == -* ]] ; then
       ^-- SC2039: In POSIX sh, [[ ]] is undefined.
 
Line 9:
        COMPREPLY=( $(compgen -W "${opts}" -- ${cur}) )
                  ^-- SC2039: In POSIX sh, arrays are undefined.
                    ^-- SC2207: Prefer mapfile or read -a to split command output (or quote to avoid splitting).
                      ^-- SC2039: In POSIX sh, 'compgen' is undefined.
                                              ^-- SC2086: Double quote to prevent globbing and word splitting.

Did you mean: (apply this, apply all SC2086)
        COMPREPLY=( $(compgen -W "${opts}" -- "${cur}") )
 
Line 11:
    elif [[ ${cur} == r* ]]; then
         ^-- SC2039: In POSIX sh, [[ ]] is undefined.
 
Line 12:
        COMPREPLY=( $(compgen -W "${opts}" ${cur}) )
                  ^-- SC2039: In POSIX sh, arrays are undefined.
                    ^-- SC2207: Prefer mapfile or read -a to split command output (or quote to avoid splitting).
                      ^-- SC2039: In POSIX sh, 'compgen' is undefined.
                                           ^-- SC2086: Double quote to prevent globbing and word splitting.

Did you mean: (apply this, apply all SC2086)
        COMPREPLY=( $(compgen -W "${opts}" "${cur}") )
 
Line 16:
complete -F _dockerfreeze dockerfreeze
^-- SC2039: In POSIX sh, 'complete' is undefined.
```

See https://shellcheck.net/?id=cb45071 

Sidenote: You merged lisas after this which won't trigger because they are set to trigger on file change in merge request.
image

**Comment by JesterOrNot** [comment]
Sorry, I'll fix it

**Pull request merged**
